export type Product = {
  id: string;
  sku: string;
  name: string;
  slug: string;
  description?: string | undefined;
  originalPrice: number;
  price: number;
  discountPercent?: number | undefined;
  currency?: string;
  stock?: number;
  sold?: number;
  isAvailable?: boolean;
  rating: number;
  reviewCount?: number;
  categoryId?: string | undefined;
  categoryName?: string | undefined;
  brandId: string;
  brandName: string;
  thumbnail: string;
  tags?: string[];
  createdAt?: string;
  updatedAt?: string;
};
